# Form implementation generated from reading ui file 'D:\UEL\VI Semester\course-management-ml-Course\course-management-ml-Course\Login\Login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(302, 447)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(6, 6, 291, 411))
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.stackedWidget.setStyleSheet("QStackedWidget {\n"
"background-color: rgb(255, 255, 255)\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Welcome = QtWidgets.QWidget()
        self.Welcome.setObjectName("Welcome")
        self.gridLayout = QtWidgets.QGridLayout(self.Welcome)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.image1 = QtWidgets.QLabel(parent=self.Welcome)
        self.image1.setText("")
        self.image1.setPixmap(QtGui.QPixmap("C:/Users/ADMIN/Pictures/Final_project/tải xuống.png"))
        self.image1.setScaledContents(True)
        self.image1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.image1.setObjectName("image1")
        self.gridLayout.addWidget(self.image1, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.Welcome)
        self.frame_3.setStyleSheet("QFrame {\n"
"border: None\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_Login = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_Login.setStyleSheet("QPushButton {\n"
"font-size: 14px\n"
"}")
        self.btn_Login.setObjectName("btn_Login")
        self.horizontalLayout_3.addWidget(self.btn_Login)
        self.btn_Register = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_Register.setStyleSheet("QPushButton {\n"
"font-size: 14px\n"
"}")
        self.btn_Register.setObjectName("btn_Register")
        self.horizontalLayout_3.addWidget(self.btn_Register)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.Welcome)
        self.frame_4.setStyleSheet("QFrame {\n"
"border: None\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout.addWidget(self.frame_4, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.Welcome)
        self.Login = QtWidgets.QWidget()
        self.Login.setObjectName("Login")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Login)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_Back = QtWidgets.QPushButton(parent=self.Login)
        self.btn_Back.setStyleSheet("QPushButton {\n"
"background: transparent;\n"
"border: none;\n"
"color: #rgb(123, 123, 123);\n"
"font-size: 12px;\n"
"text-align: left;\n"
"}\n"
"\n"
"")
        self.btn_Back.setObjectName("btn_Back")
        self.verticalLayout.addWidget(self.btn_Back)
        self.image2 = QtWidgets.QLabel(parent=self.Login)
        self.image2.setText("")
        self.image2.setPixmap(QtGui.QPixmap("C:/Users/ADMIN/Pictures/Final_project/tải xuống.png"))
        self.image2.setScaledContents(True)
        self.image2.setObjectName("image2")
        self.verticalLayout.addWidget(self.image2)
        self.label_1 = QtWidgets.QLabel(parent=self.Login)
        self.label_1.setStyleSheet("QLabel {\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.label_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(parent=self.Login)
        self.label_2.setStyleSheet("QLabel {\n"
"font-size: 14px;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Email_Label = QtWidgets.QLabel(parent=self.Login)
        self.Email_Label.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.Email_Label.setObjectName("Email_Label")
        self.verticalLayout.addWidget(self.Email_Label)
        self.Email_LineEdit = QtWidgets.QLineEdit(parent=self.Login)
        self.Email_LineEdit.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.Email_LineEdit.setObjectName("Email_LineEdit")
        self.verticalLayout.addWidget(self.Email_LineEdit)
        self.Password_Label = QtWidgets.QLabel(parent=self.Login)
        self.Password_Label.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.Password_Label.setObjectName("Password_Label")
        self.verticalLayout.addWidget(self.Password_Label)
        self.Password_LineEdit = QtWidgets.QLineEdit(parent=self.Login)
        self.Password_LineEdit.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.Password_LineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Password_LineEdit.setObjectName("Password_LineEdit")
        self.verticalLayout.addWidget(self.Password_LineEdit)
        self.btn_ForgotPass = QtWidgets.QPushButton(parent=self.Login)
        self.btn_ForgotPass.setStyleSheet("QPushButton {\n"
"background: transparent;\n"
"border: none;\n"
"color: #rgb(123, 123, 123);\n"
"font-size: 12px;\n"
"text-align: right;\n"
"}\n"
"\n"
"")
        self.btn_ForgotPass.setObjectName("btn_ForgotPass")
        self.verticalLayout.addWidget(self.btn_ForgotPass)
        self.frame_6 = QtWidgets.QFrame(parent=self.Login)
        self.frame_6.setStyleSheet("QFrame {\n"
"border:None\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(66, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.btn_Login_2 = QtWidgets.QPushButton(parent=self.frame_6)
        self.btn_Login_2.setStyleSheet("QPushButton {\n"
"font-size: 14px;\n"
"}")
        self.btn_Login_2.setObjectName("btn_Login_2")
        self.horizontalLayout_6.addWidget(self.btn_Login_2)
        spacerItem1 = QtWidgets.QSpacerItem(83, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_6.setStretch(0, 4)
        self.horizontalLayout_6.setStretch(1, 4)
        self.horizontalLayout_6.setStretch(2, 4)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame = QtWidgets.QFrame(parent=self.Login)
        self.frame.setStyleSheet("QFrame {\n"
"border:None\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.btn_Register_2 = QtWidgets.QPushButton(parent=self.frame)
        self.btn_Register_2.setStyleSheet("QPushButton {\n"
"    text-decoration: underline;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"border: none;\n"
"color: #rgb(123, 123, 123);\n"
"font-size: 12px;\n"
"text-align: left\n"
"}\n"
"\n"
"")
        self.btn_Register_2.setAutoExclusive(False)
        self.btn_Register_2.setObjectName("btn_Register_2")
        self.horizontalLayout.addWidget(self.btn_Register_2)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 4)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(1, 2)
        self.stackedWidget.addWidget(self.Login)
        self.Register = QtWidgets.QWidget()
        self.Register.setObjectName("Register")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Register)
        self.verticalLayout_2.setContentsMargins(-1, 8, -1, 4)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_Back_2 = QtWidgets.QPushButton(parent=self.Register)
        self.btn_Back_2.setStyleSheet("QPushButton {\n"
"background: transparent;\n"
"border: none;\n"
"color: #rgb(123, 123, 123);\n"
"font-size: 12px;\n"
"text-align: left;\n"
"}\n"
"\n"
"")
        self.btn_Back_2.setObjectName("btn_Back_2")
        self.verticalLayout_2.addWidget(self.btn_Back_2)
        self.image3 = QtWidgets.QLabel(parent=self.Register)
        self.image3.setText("")
        self.image3.setPixmap(QtGui.QPixmap("C:/Users/ADMIN/Pictures/Final_project/tải xuống.png"))
        self.image3.setScaledContents(True)
        self.image3.setObjectName("image3")
        self.verticalLayout_2.addWidget(self.image3)
        self.label_7 = QtWidgets.QLabel(parent=self.Register)
        self.label_7.setStyleSheet("QLabel {\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_4 = QtWidgets.QLabel(parent=self.Register)
        self.label_4.setStyleSheet("QLabel {\n"
"font-size: 14px;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.UserName_Label = QtWidgets.QLabel(parent=self.Register)
        self.UserName_Label.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.UserName_Label.setObjectName("UserName_Label")
        self.verticalLayout_2.addWidget(self.UserName_Label)
        self.UserName_LineEdit = QtWidgets.QLineEdit(parent=self.Register)
        self.UserName_LineEdit.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.UserName_LineEdit.setObjectName("UserName_LineEdit")
        self.verticalLayout_2.addWidget(self.UserName_LineEdit)
        self.Email_Label_2 = QtWidgets.QLabel(parent=self.Register)
        self.Email_Label_2.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.Email_Label_2.setObjectName("Email_Label_2")
        self.verticalLayout_2.addWidget(self.Email_Label_2)
        self.Email_LineEdit_2 = QtWidgets.QLineEdit(parent=self.Register)
        self.Email_LineEdit_2.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.Email_LineEdit_2.setObjectName("Email_LineEdit_2")
        self.verticalLayout_2.addWidget(self.Email_LineEdit_2)
        self.Password_Label_2 = QtWidgets.QLabel(parent=self.Register)
        self.Password_Label_2.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.Password_Label_2.setObjectName("Password_Label_2")
        self.verticalLayout_2.addWidget(self.Password_Label_2)
        self.Password_LineEdit_2 = QtWidgets.QLineEdit(parent=self.Register)
        self.Password_LineEdit_2.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.Password_LineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Password_LineEdit_2.setObjectName("Password_LineEdit_2")
        self.verticalLayout_2.addWidget(self.Password_LineEdit_2)
        self.frame_5 = QtWidgets.QFrame(parent=self.Register)
        self.frame_5.setStyleSheet("QFrame {\n"
"border:None\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(77, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.btn_Register_4 = QtWidgets.QPushButton(parent=self.frame_5)
        self.btn_Register_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_Register_4.setStyleSheet("QPushButton {\n"
"font-size: 14px;\n"
"}")
        self.btn_Register_4.setObjectName("btn_Register_4")
        self.horizontalLayout_5.addWidget(self.btn_Register_4)
        spacerItem3 = QtWidgets.QSpacerItem(76, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 8)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_2 = QtWidgets.QFrame(parent=self.Register)
        self.frame_2.setStyleSheet("QFrame {\n"
"border:None\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_5.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.btn_Login_3 = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_Login_3.setStyleSheet("QPushButton {\n"
"    text-decoration: underline;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"background: transparent;\n"
"border: none;\n"
"color: #rgb(123, 123, 123);\n"
"font-size: 12px;\n"
"text-align: left\n"
"}\n"
"\n"
"")
        self.btn_Login_3.setObjectName("btn_Login_3")
        self.horizontalLayout_2.addWidget(self.btn_Login_3)
        self.horizontalLayout_2.setStretch(0, 7)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_2.setStretch(1, 1)
        self.stackedWidget.addWidget(self.Register)
        self.Reset_Password = QtWidgets.QWidget()
        self.Reset_Password.setObjectName("Reset_Password")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Reset_Password)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_Back_3 = QtWidgets.QPushButton(parent=self.Reset_Password)
        self.btn_Back_3.setStyleSheet("QPushButton {\n"
"background: transparent;\n"
"border: none;\n"
"color: #rgb(123, 123, 123);\n"
"font-size: 12px;\n"
"text-align: left;\n"
"}\n"
"\n"
"")
        self.btn_Back_3.setObjectName("btn_Back_3")
        self.verticalLayout_3.addWidget(self.btn_Back_3)
        self.image4 = QtWidgets.QLabel(parent=self.Reset_Password)
        self.image4.setText("")
        self.image4.setPixmap(QtGui.QPixmap("C:/Users/ADMIN/Pictures/Final_project/tải xuống.png"))
        self.image4.setScaledContents(True)
        self.image4.setObjectName("image4")
        self.verticalLayout_3.addWidget(self.image4)
        self.label_6 = QtWidgets.QLabel(parent=self.Reset_Password)
        self.label_6.setStyleSheet("QLabel {\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.NewPassword_Label = QtWidgets.QLabel(parent=self.Reset_Password)
        self.NewPassword_Label.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.NewPassword_Label.setObjectName("NewPassword_Label")
        self.verticalLayout_3.addWidget(self.NewPassword_Label)
        self.NewPassword_LineEdit = QtWidgets.QLineEdit(parent=self.Reset_Password)
        self.NewPassword_LineEdit.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.NewPassword_LineEdit.setObjectName("NewPassword_LineEdit")
        self.verticalLayout_3.addWidget(self.NewPassword_LineEdit)
        self.RePassword_Label = QtWidgets.QLabel(parent=self.Reset_Password)
        self.RePassword_Label.setStyleSheet("QLabel {\n"
"font-size: 12px;\n"
"}")
        self.RePassword_Label.setObjectName("RePassword_Label")
        self.verticalLayout_3.addWidget(self.RePassword_Label)
        self.RePassword_LineEdit = QtWidgets.QLineEdit(parent=self.Reset_Password)
        self.RePassword_LineEdit.setStyleSheet("QLineEdit {\n"
"font-size: 12px\n"
"}")
        self.RePassword_LineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.RePassword_LineEdit.setObjectName("RePassword_LineEdit")
        self.verticalLayout_3.addWidget(self.RePassword_LineEdit)
        self.frame_7 = QtWidgets.QFrame(parent=self.Reset_Password)
        self.frame_7.setStyleSheet("QFrame {\n"
"border:None\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(83, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.Finish_btn = QtWidgets.QPushButton(parent=self.frame_7)
        self.Finish_btn.setStyleSheet("QPushButton {\n"
"font-size: 14px;\n"
"}")
        self.Finish_btn.setObjectName("Finish_btn")
        self.horizontalLayout_7.addWidget(self.Finish_btn)
        spacerItem5 = QtWidgets.QSpacerItem(83, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 4)
        self.horizontalLayout_7.setStretch(2, 4)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(4, 1)
        self.verticalLayout_3.setStretch(5, 1)
        self.verticalLayout_3.setStretch(6, 1)
        self.verticalLayout_3.setStretch(7, 1)
        self.stackedWidget.addWidget(self.Reset_Password)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 302, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Login.setText(_translate("MainWindow", "Login"))
        self.btn_Register.setText(_translate("MainWindow", "Register"))
        self.btn_Back.setText(_translate("MainWindow", "< Back"))
        self.label_1.setText(_translate("MainWindow", "Hello"))
        self.label_2.setText(_translate("MainWindow", "Sign into your Account"))
        self.Email_Label.setText(_translate("MainWindow", "Email:"))
        self.Password_Label.setText(_translate("MainWindow", "Password:"))
        self.btn_ForgotPass.setText(_translate("MainWindow", "Forgot your password?"))
        self.btn_Login_2.setText(_translate("MainWindow", "Login"))
        self.label_3.setText(_translate("MainWindow", "Don\'t have an account ?"))
        self.btn_Register_2.setText(_translate("MainWindow", "Register now"))
        self.btn_Back_2.setText(_translate("MainWindow", "< Back"))
        self.label_7.setText(_translate("MainWindow", "Hello"))
        self.label_4.setText(_translate("MainWindow", "Create New Account"))
        self.UserName_Label.setText(_translate("MainWindow", "User Name:"))
        self.Email_Label_2.setText(_translate("MainWindow", "Email:"))
        self.Password_Label_2.setText(_translate("MainWindow", "Password:"))
        self.btn_Register_4.setText(_translate("MainWindow", "Register"))
        self.label_5.setText(_translate("MainWindow", "Already have an account ?"))
        self.btn_Login_3.setText(_translate("MainWindow", "Login"))
        self.btn_Back_3.setText(_translate("MainWindow", "< Back"))
        self.label_6.setText(_translate("MainWindow", "Reset Password"))
        self.NewPassword_Label.setText(_translate("MainWindow", "New Password:"))
        self.RePassword_Label.setText(_translate("MainWindow", "Re - enter New Password:"))
        self.Finish_btn.setText(_translate("MainWindow", "Finish"))
