# Form implementation generated from reading ui file 'C:\Users\phamn\Documents\course-management-ml\ui\payment.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 614)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #f6f6f6;\n"
"}\n"
"QFrame {\n"
"    background-color: #f6f6f6;\n"
"}\n"
"#centralwidget{\n"
"    background-color: #f6f6f6;\n"
"}\n"
"#menu {\n"
"    background-color: #f9f9f9;\n"
"    border-right: 1px solid #e0e0e0;\n"
"}\n"
"QLabel#brand {\n"
"    color: black;\n"
"}\n"
"\n"
"#menu_analysis,\n"
"#menu_course,\n"
"#menu_payment,\n"
"#menu_student,\n"
"#menu_setting {\n"
"    text-align: left;\n"
"    padding: 8px 20px;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"#menu_analysis:hover,\n"
"#menu_course:hover,\n"
"#menu_logout:hover,\n"
"#menu_payment:hover,\n"
"#menu_student:hover,\n"
"#menu_setting:hover {\n"
"    background-color: #eaeaea;\n"
"}\n"
"#menu_logout {\n"
"    color: red;\n"
"    padding: 10px;\n"
"    text-align: left;\n"
"    border: none;\n"
"}\n"
"#menu_payment {\n"
"    background-color: #eaeaea;\n"
"}\n"
"#payment_search_lineEdit {\n"
"    background-color: #F8F8F8;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius-right: 10px;\n"
"    padding: 6px 12px;\n"
"    color: #555;\n"
"}\n"
"#payment_search_lineEdit:focus {\n"
"    border: 2px solid #A0A0A0;\n"
"}\n"
"#payment_search_comboBox {\n"
"    background-color: #2E2E2E;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2E2E2E;\n"
"    color: white;\n"
"    selection-background-color: #444444;\n"
"    selection-color: white;\n"
"}\n"
"#payment_create {\n"
"    background-color: #4C8BF5;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-weight: bold;\n"
"}\n"
"#payment_create:hover {\n"
"    background-color: #3B73E0;\n"
"}\n"
"#payment_filter {\n"
"    background-color: #F4F4F4;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    color: black;\n"
"}\n"
"#payment_filter:hover {\n"
"    background-color: #EAEAEA;\n"
"}\n"
"#header{\n"
"    background-color: #f9f9f9;\n"
"    color: black;\n"
"}\n"
"#payment_previous, #payment_next {\n"
"    background-color: white;\n"
"    color: #2E3A59;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    font-weight: 500;\n"
"}\n"
"#payment_previous:hover, #payment_next:hover {\n"
"    background-color: #F5F5F5;\n"
"}\n"
"#payment_page_1, #payment_page_2, #payment_page_3, #payment_page_8, #payment_page_9, #payment_page_10 {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #444;\n"
"    padding: 6px 10px;\n"
"}\n"
"#payment_page_1 {\n"
"    background-color: #E0E0E0;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"#space {\n"
"    color: #777;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(801, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu.setObjectName("menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout.setSpacing(11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.brand = QtWidgets.QLabel(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brand.sizePolicy().hasHeightForWidth())
        self.brand.setSizePolicy(sizePolicy)
        self.brand.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.brand.setFont(font)
        self.brand.setStyleSheet("")
        self.brand.setText("")
        self.brand.setPixmap(QtGui.QPixmap(":/Images/images/Logo DUKI.png"))
        self.brand.setScaledContents(True)
        self.brand.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.brand.setObjectName("brand")
        self.verticalLayout.addWidget(self.brand)
        self.line_1 = QtWidgets.QFrame(parent=self.menu)
        self.line_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout.addWidget(self.line_1)
        self.frame_2 = QtWidgets.QFrame(parent=self.menu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menu_course = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_course.sizePolicy().hasHeightForWidth())
        self.menu_course.setSizePolicy(sizePolicy)
        self.menu_course.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/Course.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_course.setIcon(icon)
        self.menu_course.setObjectName("menu_course")
        self.verticalLayout_3.addWidget(self.menu_course)
        self.menu_student = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_student.sizePolicy().hasHeightForWidth())
        self.menu_student.setSizePolicy(sizePolicy)
        self.menu_student.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.menu_student.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/Student1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_student.setIcon(icon1)
        self.menu_student.setObjectName("menu_student")
        self.verticalLayout_3.addWidget(self.menu_student)
        self.menu_analysis = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_analysis.sizePolicy().hasHeightForWidth())
        self.menu_analysis.setSizePolicy(sizePolicy)
        self.menu_analysis.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/Analysis.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_analysis.setIcon(icon2)
        self.menu_analysis.setObjectName("menu_analysis")
        self.verticalLayout_3.addWidget(self.menu_analysis)
        self.menu_payment = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_payment.sizePolicy().hasHeightForWidth())
        self.menu_payment.setSizePolicy(sizePolicy)
        self.menu_payment.setMinimumSize(QtCore.QSize(150, 28))
        self.menu_payment.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/Payment.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_payment.setIcon(icon3)
        self.menu_payment.setObjectName("menu_payment")
        self.verticalLayout_3.addWidget(self.menu_payment)
        self.verticalLayout.addWidget(self.frame_2)
        self.line_2 = QtWidgets.QFrame(parent=self.menu)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.menu_setting = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_setting.sizePolicy().hasHeightForWidth())
        self.menu_setting.setSizePolicy(sizePolicy)
        self.menu_setting.setMinimumSize(QtCore.QSize(60, 12))
        self.menu_setting.setStyleSheet("")
        self.menu_setting.setObjectName("menu_setting")
        self.verticalLayout.addWidget(self.menu_setting)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.menu_logout = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_logout.sizePolicy().hasHeightForWidth())
        self.menu_logout.setSizePolicy(sizePolicy)
        self.menu_logout.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.menu_logout.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/Log_Out.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_logout.setIcon(icon4)
        self.menu_logout.setObjectName("menu_logout")
        self.verticalLayout.addWidget(self.menu_logout)
        self.horizontalLayout.addWidget(self.menu)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QLabel(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.header.setFont(font)
        self.header.setObjectName("header")
        self.verticalLayout_2.addWidget(self.header)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(165, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.payment_table = QtWidgets.QTableWidget(parent=self.frame_6)
        self.payment_table.setStyleSheet("color: black")
        self.payment_table.setObjectName("payment_table")
        self.payment_table.setColumnCount(7)
        self.payment_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.payment_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.payment_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.payment_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.payment_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.payment_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.payment_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.payment_table.setHorizontalHeaderItem(6, item)
        self.payment_table.horizontalHeader().setDefaultSectionSize(150)
        self.horizontalLayout_8.addWidget(self.payment_table)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.payment_previous = QtWidgets.QPushButton(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payment_previous.sizePolicy().hasHeightForWidth())
        self.payment_previous.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/le-Photoroom.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.payment_previous.setIcon(icon5)
        self.payment_previous.setObjectName("payment_previous")
        self.horizontalLayout_6.addWidget(self.payment_previous)
        spacerItem2 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.payment_page = QtWidgets.QWidget(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payment_page.sizePolicy().hasHeightForWidth())
        self.payment_page.setSizePolicy(sizePolicy)
        self.payment_page.setMinimumSize(QtCore.QSize(350, 0))
        self.payment_page.setObjectName("payment_page")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.payment_page)
        self.horizontalLayout_7.setContentsMargins(11, -1, 11, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.payment_page_1 = QtWidgets.QPushButton(parent=self.payment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payment_page_1.sizePolicy().hasHeightForWidth())
        self.payment_page_1.setSizePolicy(sizePolicy)
        self.payment_page_1.setMinimumSize(QtCore.QSize(28, 0))
        self.payment_page_1.setObjectName("payment_page_1")
        self.horizontalLayout_7.addWidget(self.payment_page_1)
        self.payment_page_2 = QtWidgets.QPushButton(parent=self.payment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payment_page_2.sizePolicy().hasHeightForWidth())
        self.payment_page_2.setSizePolicy(sizePolicy)
        self.payment_page_2.setMinimumSize(QtCore.QSize(28, 0))
        self.payment_page_2.setObjectName("payment_page_2")
        self.horizontalLayout_7.addWidget(self.payment_page_2)
        self.payment_page_8 = QtWidgets.QPushButton(parent=self.payment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payment_page_8.sizePolicy().hasHeightForWidth())
        self.payment_page_8.setSizePolicy(sizePolicy)
        self.payment_page_8.setMinimumSize(QtCore.QSize(28, 0))
        self.payment_page_8.setObjectName("payment_page_8")
        self.horizontalLayout_7.addWidget(self.payment_page_8)
        self.payment_space = QtWidgets.QLabel(parent=self.payment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payment_space.sizePolicy().hasHeightForWidth())
        self.payment_space.setSizePolicy(sizePolicy)
        self.payment_space.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.payment_space.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.payment_space.setObjectName("payment_space")
        self.horizontalLayout_7.addWidget(self.payment_space)
        self.payment_page_10 = QtWidgets.QPushButton(parent=self.payment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payment_page_10.sizePolicy().hasHeightForWidth())
        self.payment_page_10.setSizePolicy(sizePolicy)
        self.payment_page_10.setMinimumSize(QtCore.QSize(28, 0))
        self.payment_page_10.setObjectName("payment_page_10")
        self.horizontalLayout_7.addWidget(self.payment_page_10)
        self.payment_page_9 = QtWidgets.QPushButton(parent=self.payment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payment_page_9.sizePolicy().hasHeightForWidth())
        self.payment_page_9.setSizePolicy(sizePolicy)
        self.payment_page_9.setMinimumSize(QtCore.QSize(28, 0))
        self.payment_page_9.setObjectName("payment_page_9")
        self.horizontalLayout_7.addWidget(self.payment_page_9)
        self.payment_page_3 = QtWidgets.QPushButton(parent=self.payment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payment_page_3.sizePolicy().hasHeightForWidth())
        self.payment_page_3.setSizePolicy(sizePolicy)
        self.payment_page_3.setMinimumSize(QtCore.QSize(28, 0))
        self.payment_page_3.setObjectName("payment_page_3")
        self.horizontalLayout_7.addWidget(self.payment_page_3)
        self.horizontalLayout_6.addWidget(self.payment_page)
        spacerItem3 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.payment_next = QtWidgets.QPushButton(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payment_next.sizePolicy().hasHeightForWidth())
        self.payment_next.setSizePolicy(sizePolicy)
        self.payment_next.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/ri-Photoroom.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.payment_next.setIcon(icon6)
        self.payment_next.setObjectName("payment_next")
        self.horizontalLayout_6.addWidget(self.payment_next)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame_3)
        self.horizontalLayout_5.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_course.setText(_translate("MainWindow", "Course"))
        self.menu_student.setText(_translate("MainWindow", "Student"))
        self.menu_analysis.setText(_translate("MainWindow", "Analysis"))
        self.menu_payment.setText(_translate("MainWindow", "Payment*"))
        self.menu_setting.setText(_translate("MainWindow", "Setting*"))
        self.menu_logout.setText(_translate("MainWindow", "Log out"))
        self.header.setText(_translate("MainWindow", " Payment"))
        item = self.payment_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID Invoice"))
        item = self.payment_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID Student"))
        item = self.payment_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Code Module"))
        item = self.payment_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Code Presentation"))
        item = self.payment_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        item = self.payment_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.payment_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status"))
        self.payment_previous.setText(_translate("MainWindow", "Previous"))
        self.payment_page_1.setText(_translate("MainWindow", "1"))
        self.payment_page_2.setText(_translate("MainWindow", "2"))
        self.payment_page_8.setText(_translate("MainWindow", "3"))
        self.payment_space.setText(_translate("MainWindow", "..."))
        self.payment_page_10.setText(_translate("MainWindow", "8"))
        self.payment_page_9.setText(_translate("MainWindow", "9"))
        self.payment_page_3.setText(_translate("MainWindow", "10"))
        self.payment_next.setText(_translate("MainWindow", "   Next "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
