# Form implementation generated from reading ui file 'C:\Users\phamn\Documents\ML_final\ui\analysis.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 614)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #f6f6f6;\n"
"}\n"
"QFrame {\n"
"    background-color: #f6f6f6;\n"
"}\n"
"#centralwidget{\n"
"    background-color: #f6f6f6;\n"
"}\n"
"#menu {\n"
"    background-color: #f9f9f9;\n"
"    border-right: 1px solid #e0e0e0;\n"
"}\n"
"QLabel#brand {\n"
"    color: black;\n"
"}\n"
"\n"
"#menu_analysis,\n"
"#menu_course,\n"
"#menu_payment,\n"
"#menu_student,\n"
"#menu_setting {\n"
"    text-align: left;\n"
"    padding: 8px 20px;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"#menu_analysis:hover,\n"
"#menu_course:hover,\n"
"#menu_logout:hover,\n"
"#menu_payment:hover,\n"
"#menu_student:hover,\n"
"#menu_setting:hover {\n"
"    background-color: #eaeaea;\n"
"}\n"
"#menu_logout {\n"
"    color: red;\n"
"    padding: 10px;\n"
"    text-align: left;\n"
"    border: none;\n"
"}\n"
"#menu_analysis {\n"
"    background-color: #eaeaea;\n"
"}\n"
"#analysis_search_lineEdit {\n"
"    background-color: #F8F8F8;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius-right: 10px;\n"
"    padding: 6px 12px;\n"
"    color: #555;\n"
"}\n"
"#analysis_search_lineEdit:focus {\n"
"    border: 2px solid #A0A0A0;\n"
"}\n"
"#analysis_search_comboBox {\n"
"    background-color: #2E2E2E;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2E2E2E;\n"
"    color: white;\n"
"    selection-background-color: #444444;\n"
"    selection-color: white;\n"
"}\n"
"#analysis_create {\n"
"    background-color: #4C8BF5;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-weight: bold;\n"
"}\n"
"#analysis_create:hover {\n"
"    background-color: #3B73E0;\n"
"}\n"
"#analysis_filter {\n"
"    background-color: #F4F4F4;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    color: black;\n"
"}\n"
"#analysis_filter:hover {\n"
"    background-color: #EAEAEA;\n"
"}\n"
"#header{\n"
"    background-color: #f9f9f9;\n"
"    color: black;\n"
"}\n"
"#analysis_previous, #analysis_next {\n"
"    background-color: white;\n"
"    color: #2E3A59;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    font-weight: 500;\n"
"}\n"
"#analysis_previous:hover, #analysis_next:hover {\n"
"    background-color: #F5F5F5;\n"
"}\n"
"#analysis_page_1, #analysis_page_2, #analysis_page_3, #analysis_page_8, #analysis_page_9, #analysis_page_10 {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #444;\n"
"    padding: 6px 10px;\n"
"}\n"
"#analysis_page_1 {\n"
"    background-color: #E0E0E0;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"#space {\n"
"    color: #777;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(801, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu.setObjectName("menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout.setSpacing(11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.brand = QtWidgets.QLabel(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brand.sizePolicy().hasHeightForWidth())
        self.brand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.brand.setFont(font)
        self.brand.setStyleSheet("")
        self.brand.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.brand.setObjectName("brand")
        self.verticalLayout.addWidget(self.brand)
        self.line_1 = QtWidgets.QFrame(parent=self.menu)
        self.line_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout.addWidget(self.line_1)
        self.frame_2 = QtWidgets.QFrame(parent=self.menu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menu_course = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_course.sizePolicy().hasHeightForWidth())
        self.menu_course.setSizePolicy(sizePolicy)
        self.menu_course.setStyleSheet("")
        self.menu_course.setObjectName("menu_course")
        self.verticalLayout_3.addWidget(self.menu_course)
        self.menu_student = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_student.sizePolicy().hasHeightForWidth())
        self.menu_student.setSizePolicy(sizePolicy)
        self.menu_student.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.menu_student.setStyleSheet("")
        self.menu_student.setObjectName("menu_student")
        self.verticalLayout_3.addWidget(self.menu_student)
        self.menu_analysis = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_analysis.sizePolicy().hasHeightForWidth())
        self.menu_analysis.setSizePolicy(sizePolicy)
        self.menu_analysis.setStyleSheet("")
        self.menu_analysis.setObjectName("menu_analysis")
        self.verticalLayout_3.addWidget(self.menu_analysis)
        self.menu_payment = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_payment.sizePolicy().hasHeightForWidth())
        self.menu_payment.setSizePolicy(sizePolicy)
        self.menu_payment.setMinimumSize(QtCore.QSize(150, 28))
        self.menu_payment.setStyleSheet("")
        self.menu_payment.setObjectName("menu_payment")
        self.verticalLayout_3.addWidget(self.menu_payment)
        self.verticalLayout.addWidget(self.frame_2)
        self.line_2 = QtWidgets.QFrame(parent=self.menu)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.menu_setting = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_setting.sizePolicy().hasHeightForWidth())
        self.menu_setting.setSizePolicy(sizePolicy)
        self.menu_setting.setMinimumSize(QtCore.QSize(60, 12))
        self.menu_setting.setStyleSheet("")
        self.menu_setting.setObjectName("menu_setting")
        self.verticalLayout.addWidget(self.menu_setting)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.menu_logout = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_logout.sizePolicy().hasHeightForWidth())
        self.menu_logout.setSizePolicy(sizePolicy)
        self.menu_logout.setStyleSheet("")
        self.menu_logout.setObjectName("menu_logout")
        self.verticalLayout.addWidget(self.menu_logout)
        self.horizontalLayout.addWidget(self.menu)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_2.addItem(spacerItem1)
        self.header = QtWidgets.QLabel(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.header.setFont(font)
        self.header.setObjectName("header")
        self.verticalLayout_2.addWidget(self.header)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(165, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget = QtWidgets.QWidget(parent=self.frame_6)
        self.widget.setObjectName("widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cluster_analysis_chart = QtWidgets.QWidget(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cluster_analysis_chart.sizePolicy().hasHeightForWidth())
        self.cluster_analysis_chart.setSizePolicy(sizePolicy)
        self.cluster_analysis_chart.setMinimumSize(QtCore.QSize(0, 0))
        self.cluster_analysis_chart.setStyleSheet("    background-color: white;\n"
"    border: 1px solid #dcdcdc;   /* viền xám nhạt */\n"
"    border-radius: 12px;          /* bo tròn góc */")
        self.cluster_analysis_chart.setObjectName("cluster_analysis_chart")
        self.horizontalLayout_9.addWidget(self.cluster_analysis_chart)
        self.frame_4 = QtWidgets.QFrame(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cluster_analysis_groupA = QtWidgets.QFrame(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cluster_analysis_groupA.sizePolicy().hasHeightForWidth())
        self.cluster_analysis_groupA.setSizePolicy(sizePolicy)
        self.cluster_analysis_groupA.setStyleSheet("    background-color: white;\n"
"    border: 1px solid #dcdcdc;   /* viền xám nhạt */\n"
"    border-radius: 12px;          /* bo tròn góc */")
        self.cluster_analysis_groupA.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cluster_analysis_groupA.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cluster_analysis_groupA.setObjectName("cluster_analysis_groupA")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.cluster_analysis_groupA)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(parent=self.cluster_analysis_groupA)
        self.label.setStyleSheet("border: none;\n"
"color: black")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.count_groupA = QtWidgets.QLabel(parent=self.cluster_analysis_groupA)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.count_groupA.setFont(font)
        self.count_groupA.setStyleSheet("border: None;\n"
"color: black")
        self.count_groupA.setObjectName("count_groupA")
        self.verticalLayout_5.addWidget(self.count_groupA)
        self.verticalLayout_4.addWidget(self.cluster_analysis_groupA)
        self.cluster_analysis_groupB = QtWidgets.QFrame(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cluster_analysis_groupB.sizePolicy().hasHeightForWidth())
        self.cluster_analysis_groupB.setSizePolicy(sizePolicy)
        self.cluster_analysis_groupB.setStyleSheet("    background-color: white;\n"
"    border: 1px solid #dcdcdc;   /* viền xám nhạt */\n"
"    border-radius: 12px;          /* bo tròn góc */")
        self.cluster_analysis_groupB.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cluster_analysis_groupB.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cluster_analysis_groupB.setObjectName("cluster_analysis_groupB")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.cluster_analysis_groupB)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(parent=self.cluster_analysis_groupB)
        self.label_11.setStyleSheet("border: none;\n"
"color: black")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.count_groupB = QtWidgets.QLabel(parent=self.cluster_analysis_groupB)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.count_groupB.setFont(font)
        self.count_groupB.setStyleSheet("border: None;\n"
"color: black")
        self.count_groupB.setObjectName("count_groupB")
        self.verticalLayout_10.addWidget(self.count_groupB)
        self.verticalLayout_4.addWidget(self.cluster_analysis_groupB)
        self.cluster_analysis_groupC = QtWidgets.QFrame(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cluster_analysis_groupC.sizePolicy().hasHeightForWidth())
        self.cluster_analysis_groupC.setSizePolicy(sizePolicy)
        self.cluster_analysis_groupC.setStyleSheet("    background-color: white;\n"
"    border: 1px solid #dcdcdc;   /* viền xám nhạt */\n"
"    border-radius: 12px;          /* bo tròn góc */")
        self.cluster_analysis_groupC.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cluster_analysis_groupC.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cluster_analysis_groupC.setObjectName("cluster_analysis_groupC")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.cluster_analysis_groupC)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(parent=self.cluster_analysis_groupC)
        self.label_7.setStyleSheet("border: none;\n"
"color: black")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.count_groupC = QtWidgets.QLabel(parent=self.cluster_analysis_groupC)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.count_groupC.setFont(font)
        self.count_groupC.setStyleSheet("border: None;\n"
"color: black")
        self.count_groupC.setObjectName("count_groupC")
        self.verticalLayout_8.addWidget(self.count_groupC)
        self.verticalLayout_4.addWidget(self.cluster_analysis_groupC)
        self.cluster_analysis_groupD = QtWidgets.QFrame(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cluster_analysis_groupD.sizePolicy().hasHeightForWidth())
        self.cluster_analysis_groupD.setSizePolicy(sizePolicy)
        self.cluster_analysis_groupD.setStyleSheet("    background-color: white;\n"
"    border: 1px solid #dcdcdc;   /* viền xám nhạt */\n"
"    border-radius: 12px;          /* bo tròn góc */")
        self.cluster_analysis_groupD.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cluster_analysis_groupD.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cluster_analysis_groupD.setObjectName("cluster_analysis_groupD")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.cluster_analysis_groupD)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(parent=self.cluster_analysis_groupD)
        self.label_5.setStyleSheet("border: none;\n"
"color: black")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.count_groupD = QtWidgets.QLabel(parent=self.cluster_analysis_groupD)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.count_groupD.setFont(font)
        self.count_groupD.setStyleSheet("border: None;\n"
"color: black")
        self.count_groupD.setObjectName("count_groupD")
        self.verticalLayout_7.addWidget(self.count_groupD)
        self.verticalLayout_4.addWidget(self.cluster_analysis_groupD)
        self.cluster_analysis_groupE = QtWidgets.QFrame(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cluster_analysis_groupE.sizePolicy().hasHeightForWidth())
        self.cluster_analysis_groupE.setSizePolicy(sizePolicy)
        self.cluster_analysis_groupE.setStyleSheet("    background-color: white;\n"
"    border: 1px solid #dcdcdc;   /* viền xám nhạt */\n"
"    border-radius: 12px;          /* bo tròn góc */")
        self.cluster_analysis_groupE.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cluster_analysis_groupE.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cluster_analysis_groupE.setObjectName("cluster_analysis_groupE")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.cluster_analysis_groupE)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(parent=self.cluster_analysis_groupE)
        self.label_9.setStyleSheet("border: none;\n"
"color: black")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.count_groupE = QtWidgets.QLabel(parent=self.cluster_analysis_groupE)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.count_groupE.setFont(font)
        self.count_groupE.setStyleSheet("border: None;\n"
"color: black")
        self.count_groupE.setObjectName("count_groupE")
        self.verticalLayout_9.addWidget(self.count_groupE)
        self.verticalLayout_4.addWidget(self.cluster_analysis_groupE)
        self.horizontalLayout_9.addWidget(self.frame_4)
        self.horizontalLayout_9.setStretch(0, 10)
        self.horizontalLayout_9.setStretch(1, 4)
        self.horizontalLayout_8.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame_3)
        self.horizontalLayout_5.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.brand.setText(_translate("MainWindow", "DUKI"))
        self.menu_course.setText(_translate("MainWindow", "Course"))
        self.menu_student.setText(_translate("MainWindow", "Student"))
        self.menu_analysis.setText(_translate("MainWindow", "Analysis"))
        self.menu_payment.setText(_translate("MainWindow", "Payment"))
        self.menu_setting.setText(_translate("MainWindow", "Setting"))
        self.menu_logout.setText(_translate("MainWindow", "Log out"))
        self.header.setText(_translate("MainWindow", " Analysis"))
        self.label.setText(_translate("MainWindow", "Group A"))
        self.count_groupA.setText(_translate("MainWindow", "0000"))
        self.label_11.setText(_translate("MainWindow", "Group B"))
        self.count_groupB.setText(_translate("MainWindow", "0000"))
        self.label_7.setText(_translate("MainWindow", "Group C"))
        self.count_groupC.setText(_translate("MainWindow", "0000"))
        self.label_5.setText(_translate("MainWindow", "Group D"))
        self.count_groupD.setText(_translate("MainWindow", "0000"))
        self.label_9.setText(_translate("MainWindow", "Group E"))
        self.count_groupE.setText(_translate("MainWindow", "0000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
