name: course_management
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - icu=75.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.7.1
  - libffi=3.4.6
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libsqlite=3.50.4
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.2
  - mkl=2024.2.2
  - numpy=1.26.4
  - openssl=3.5.4
  - pip=25.2
  - python=3.12.11
  - python_abi=3.12
  - setuptools=80.9.0
  - tbb=2021.13.0
  - tk=8.6.13
  - ucrt=10.0.26100.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wheel=0.45.1
  - pip:
      - catboost==1.2.8
      - colorlog==6.9.0
      - cycler==0.12.1
      - fonttools==4.60.1
      - graphviz==0.21
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lightgbm==4.6.0
      - mysql==0.0.3
      - mysql-connector-python==9.4.0
      - mysqlclient==2.2.7
      - narwhals==2.10.0
      - plotly==6.3.1
      - pyparsing==3.2.5
      - pyqt6-webengine==6.9.0
      - pyqt6-webengine-qt6==6.9.2
      - pytz==2025.2
      - scienceplots==2.1.1
      - scikit-learn==1.6.1
      - scipy==1.16.2
      - seaborn==0.13.2
      - threadpoolctl==3.6.0
      - tzdata==2025.2
      - xgboost==3.1.1
