# Form implementation generated from reading ui file 'analysis.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 614)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #f6f6f6;\n"
"}\n"
"QFrame {\n"
"    background-color: #f6f6f6;\n"
"}\n"
"#centralwidget{\n"
"    background-color: #f6f6f6;\n"
"}\n"
"#menu {\n"
"    background-color: #f9f9f9;\n"
"    border-right: 1px solid #e0e0e0;\n"
"}\n"
"QLabel#brand {\n"
"    color: black;\n"
"}\n"
"\n"
"#menu_analysis,\n"
"#menu_course,\n"
"#menu_payment,\n"
"#menu_student,\n"
"#menu_setting {\n"
"    text-align: left;\n"
"    padding: 8px 20px;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"#menu_analysis:hover,\n"
"#menu_course:hover,\n"
"#menu_logout:hover,\n"
"#menu_payment:hover,\n"
"#menu_student:hover,\n"
"#menu_setting:hover {\n"
"    background-color: #eaeaea;\n"
"}\n"
"#menu_logout {\n"
"    color: red;\n"
"    padding: 10px;\n"
"    text-align: left;\n"
"    border: none;\n"
"}\n"
"#menu_analysis {\n"
"    background-color: #eaeaea;\n"
"}\n"
"#analysis_search_lineEdit {\n"
"    background-color: #F8F8F8;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius-right: 10px;\n"
"    padding: 6px 12px;\n"
"    color: #555;\n"
"}\n"
"#analysis_search_lineEdit:focus {\n"
"    border: 2px solid #A0A0A0;\n"
"}\n"
"#analysis_search_comboBox {\n"
"    background-color: #2E2E2E;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2E2E2E;\n"
"    color: white;\n"
"    selection-background-color: #444444;\n"
"    selection-color: white;\n"
"}\n"
"#analysis_create {\n"
"    background-color: #4C8BF5;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-weight: bold;\n"
"}\n"
"#analysis_create:hover {\n"
"    background-color: #3B73E0;\n"
"}\n"
"#analysis_filter {\n"
"    background-color: #F4F4F4;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    color: black;\n"
"}\n"
"#analysis_filter:hover {\n"
"    background-color: #EAEAEA;\n"
"}\n"
"#header{\n"
"    background-color: #f9f9f9;\n"
"    color: black;\n"
"}\n"
"#analysis_previous, #analysis_next {\n"
"    background-color: white;\n"
"    color: #2E3A59;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    font-weight: 500;\n"
"}\n"
"#analysis_previous:hover, #analysis_next:hover {\n"
"    background-color: #F5F5F5;\n"
"}\n"
"#analysis_page_1, #analysis_page_2, #analysis_page_3, #analysis_page_8, #analysis_page_9, #analysis_page_10 {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #444;\n"
"    padding: 6px 10px;\n"
"}\n"
"#analysis_page_1 {\n"
"    background-color: #E0E0E0;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"#space {\n"
"    color: #777;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(801, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu.setObjectName("menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout.setSpacing(11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.brand = QtWidgets.QLabel(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brand.sizePolicy().hasHeightForWidth())
        self.brand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.brand.setFont(font)
        self.brand.setStyleSheet("")
        self.brand.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.brand.setObjectName("brand")
        self.verticalLayout.addWidget(self.brand)
        self.line_1 = QtWidgets.QFrame(parent=self.menu)
        self.line_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout.addWidget(self.line_1)
        self.frame_2 = QtWidgets.QFrame(parent=self.menu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menu_course = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_course.sizePolicy().hasHeightForWidth())
        self.menu_course.setSizePolicy(sizePolicy)
        self.menu_course.setStyleSheet("")
        self.menu_course.setObjectName("menu_course")
        self.verticalLayout_3.addWidget(self.menu_course)
        self.menu_student = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_student.sizePolicy().hasHeightForWidth())
        self.menu_student.setSizePolicy(sizePolicy)
        self.menu_student.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.menu_student.setStyleSheet("")
        self.menu_student.setObjectName("menu_student")
        self.verticalLayout_3.addWidget(self.menu_student)
        self.menu_analysis = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_analysis.sizePolicy().hasHeightForWidth())
        self.menu_analysis.setSizePolicy(sizePolicy)
        self.menu_analysis.setStyleSheet("")
        self.menu_analysis.setObjectName("menu_analysis")
        self.verticalLayout_3.addWidget(self.menu_analysis)
        self.menu_payment = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_payment.sizePolicy().hasHeightForWidth())
        self.menu_payment.setSizePolicy(sizePolicy)
        self.menu_payment.setMinimumSize(QtCore.QSize(150, 28))
        self.menu_payment.setStyleSheet("")
        self.menu_payment.setObjectName("menu_payment")
        self.verticalLayout_3.addWidget(self.menu_payment)
        self.verticalLayout.addWidget(self.frame_2)
        self.line_2 = QtWidgets.QFrame(parent=self.menu)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.menu_setting = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_setting.sizePolicy().hasHeightForWidth())
        self.menu_setting.setSizePolicy(sizePolicy)
        self.menu_setting.setMinimumSize(QtCore.QSize(60, 12))
        self.menu_setting.setStyleSheet("")
        self.menu_setting.setObjectName("menu_setting")
        self.verticalLayout.addWidget(self.menu_setting)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.menu_logout = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_logout.sizePolicy().hasHeightForWidth())
        self.menu_logout.setSizePolicy(sizePolicy)
        self.menu_logout.setStyleSheet("")
        self.menu_logout.setObjectName("menu_logout")
        self.verticalLayout.addWidget(self.menu_logout)
        self.horizontalLayout.addWidget(self.menu)
        self.central_page = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_page.sizePolicy().hasHeightForWidth())
        self.central_page.setSizePolicy(sizePolicy)
        self.central_page.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.central_page.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.central_page.setObjectName("central_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central_page)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QLabel(parent=self.central_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.header.setFont(font)
        self.header.setObjectName("header")
        self.verticalLayout_2.addWidget(self.header)
        self.main_page = QtWidgets.QFrame(parent=self.central_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_page.sizePolicy().hasHeightForWidth())
        self.main_page.setSizePolicy(sizePolicy)
        self.main_page.setMinimumSize(QtCore.QSize(165, 0))
        self.main_page.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_page.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_page.setObjectName("main_page")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.main_page)
        self.horizontalLayout_8.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.main_page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 224, 478))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 221, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.cluster_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.cluster_layout.setContentsMargins(0, 0, 0, 0)
        self.cluster_layout.setObjectName("cluster_layout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_8.addWidget(self.scrollArea)
        self.pie_chart_widget = QtWidgets.QWidget(parent=self.main_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pie_chart_widget.sizePolicy().hasHeightForWidth())
        self.pie_chart_widget.setSizePolicy(sizePolicy)
        self.pie_chart_widget.setMinimumSize(QtCore.QSize(200, 0))
        self.pie_chart_widget.setStyleSheet("    background-color: white;\n"
"    border: 1px solid #dcdcdc;   /* viền xám nhạt */\n"
"    border-radius: 12px;          /* bo tròn góc */")
        self.pie_chart_widget.setObjectName("pie_chart_widget")
        self.horizontalLayout_8.addWidget(self.pie_chart_widget)
        self.horizontalLayout_8.setStretch(0, 4)
        self.horizontalLayout_8.setStretch(1, 7)
        self.verticalLayout_2.addWidget(self.main_page)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.horizontalLayout.addWidget(self.central_page)
        self.horizontalLayout_5.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.brand.setText(_translate("MainWindow", "DUKI"))
        self.menu_course.setText(_translate("MainWindow", "Course"))
        self.menu_student.setText(_translate("MainWindow", "Student"))
        self.menu_analysis.setText(_translate("MainWindow", "Analysis"))
        self.menu_payment.setText(_translate("MainWindow", "Payment"))
        self.menu_setting.setText(_translate("MainWindow", "Setting"))
        self.menu_logout.setText(_translate("MainWindow", "Log out"))
        self.header.setText(_translate("MainWindow", " Analysis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
