# Form implementation generated from reading ui file 'cluster_detail.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ClusterDetailPageWidget(object):
    def setupUi(self, ClusterDetailPageWidget):
        ClusterDetailPageWidget.setObjectName("ClusterDetailPageWidget")
        ClusterDetailPageWidget.resize(800, 600)
        ClusterDetailPageWidget.setStyleSheet("QWidget#ClusterDetailPageWidget {\n"
"    background-color: #f6f6f6;\n"
"}\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #e0e0e0;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f9f9f9;\n"
"    padding: 4px;\n"
"    border-bottom: 1px solid #e0e0e0;\n"
"    font-weight: bold;\n"
"}\n"
"QScrollArea {\n"
"    border: 1px solid #e0e0e0;\n"
"    background-color: white;\n"
"}\n"
"QLabel#recommendation_title_label {\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"    padding: 5px;\n"
"    background-color: #f9f9f9;\n"
"    border-bottom: 1px solid #e0e0e0;\n"
"}\n"
"QLabel.course_label {\n"
"    font-size: 9pt;\n"
"    padding: 4px 8px;\n"
"    border-bottom: 1px solid #f0f0f0;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ClusterDetailPageWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.back_button = QtWidgets.QPushButton(parent=ClusterDetailPageWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_button.sizePolicy().hasHeightForWidth())
        self.back_button.setSizePolicy(sizePolicy)
        self.back_button.setObjectName("back_button")
        self.verticalLayout.addWidget(self.back_button)
        self.title_label = QtWidgets.QLabel(parent=ClusterDetailPageWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.student_table = QtWidgets.QTableWidget(parent=ClusterDetailPageWidget)
        self.student_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.student_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.student_table.setObjectName("student_table")
        self.student_table.setColumnCount(4)
        self.student_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.student_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_table.setHorizontalHeaderItem(3, item)
        self.student_table.horizontalHeader().setStretchLastSection(True)
        self.student_table.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.student_table)
        self.recommendation_scroll_area = QtWidgets.QScrollArea(parent=ClusterDetailPageWidget)
        self.recommendation_scroll_area.setWidgetResizable(True)
        self.recommendation_scroll_area.setObjectName("recommendation_scroll_area")
        self.scroll_content_widget = QtWidgets.QWidget()
        self.scroll_content_widget.setGeometry(QtCore.QRect(0, 0, 257, 485))
        self.scroll_content_widget.setObjectName("scroll_content_widget")
        self.recommendation_layout = QtWidgets.QVBoxLayout(self.scroll_content_widget)
        self.recommendation_layout.setContentsMargins(0, 0, 0, 0)
        self.recommendation_layout.setSpacing(0)
        self.recommendation_layout.setObjectName("recommendation_layout")
        self.recommendation_title_label = QtWidgets.QLabel(parent=self.scroll_content_widget)
        self.recommendation_title_label.setObjectName("recommendation_title_label")
        self.recommendation_layout.addWidget(self.recommendation_title_label)
        spacerItem = QtWidgets.QSpacerItem(20, 446, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.recommendation_layout.addItem(spacerItem)
        self.recommendation_scroll_area.setWidget(self.scroll_content_widget)
        self.horizontalLayout.addWidget(self.recommendation_scroll_area)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ClusterDetailPageWidget)
        QtCore.QMetaObject.connectSlotsByName(ClusterDetailPageWidget)

    def retranslateUi(self, ClusterDetailPageWidget):
        _translate = QtCore.QCoreApplication.translate
        ClusterDetailPageWidget.setWindowTitle(_translate("ClusterDetailPageWidget", "Form"))
        self.back_button.setText(_translate("ClusterDetailPageWidget", "<- Back to Cluster List"))
        self.title_label.setText(_translate("ClusterDetailPageWidget", "Students in Cluster X"))
        item = self.student_table.horizontalHeaderItem(0)
        item.setText(_translate("ClusterDetailPageWidget", "Student ID"))
        item = self.student_table.horizontalHeaderItem(1)
        item.setText(_translate("ClusterDetailPageWidget", "Student Name"))
        item = self.student_table.horizontalHeaderItem(2)
        item.setText(_translate("ClusterDetailPageWidget", "Study Method"))
        item = self.student_table.horizontalHeaderItem(3)
        item.setText(_translate("ClusterDetailPageWidget", "Cluster"))
        self.recommendation_title_label.setText(_translate("ClusterDetailPageWidget", "Recommendations"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClusterDetailPageWidget = QtWidgets.QWidget()
    ui = Ui_ClusterDetailPageWidget()
    ui.setupUi(ClusterDetailPageWidget)
    ClusterDetailPageWidget.show()
    sys.exit(app.exec())
