# Form implementation generated from reading ui file 'course_assessment.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 614)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #f6f6f6;\n"
"}\n"
"QFrame {\n"
"    background-color: #f6f6f6;\n"
"}\n"
"#centralwidget{\n"
"    background-color: #f6f6f6;\n"
"}\n"
"#menu {\n"
"    background-color: #f9f9f9;\n"
"    border-right: 1px solid #e0e0e0;\n"
"}\n"
"QLabel#brand {\n"
"    color: black;\n"
"}\n"
"\n"
"#menu_analysis,\n"
"#menu_course,\n"
"#menu_payment,\n"
"#menu_student,\n"
"#menu_setting {\n"
"    text-align: left;\n"
"    padding: 8px 20px;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"#menu_analysis:hover,\n"
"#menu_course:hover,\n"
"#menu_logout:hover,\n"
"#menu_payment:hover,\n"
"#menu_student:hover,\n"
"#menu_setting:hover {\n"
"    background-color: #eaeaea;\n"
"}\n"
"#menu_logout {\n"
"    color: red;\n"
"    padding: 10px;\n"
"    text-align: left;\n"
"    border: none;\n"
"}\n"
"#menu_course {\n"
"    background-color: #eaeaea;\n"
"}\n"
"#course_assessment_search_lineEdit {\n"
"    background-color: #F8F8F8;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius-right: 10px;\n"
"    padding: 6px 12px;\n"
"    color: #555;\n"
"}\n"
"#course_assessment_search_lineEdit:focus {\n"
"    border: 2px solid #A0A0A0;\n"
"}\n"
"#course_assessment_search_comboBox {\n"
"    background-color: #2E2E2E;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2E2E2E;\n"
"    color: white;\n"
"    selection-background-color: #444444;\n"
"    selection-color: white;\n"
"}\n"
"#course_assessment_create {\n"
"    background-color: #4C8BF5;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-weight: bold;\n"
"}\n"
"#course_assessment_create:hover {\n"
"    background-color: #3B73E0;\n"
"}\n"
"#course_assessment_filter {\n"
"    background-color: #F4F4F4;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    color: black;\n"
"}\n"
"#course_assessment_filter:hover {\n"
"    background-color: #EAEAEA;\n"
"}\n"
"#header{\n"
"    background-color: #f9f9f9;\n"
"    color: black;\n"
"}\n"
"#course_assessment_previous, #course_assessment_next {\n"
"    background-color: white;\n"
"    color: #2E3A59;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    font-weight: 500;\n"
"}\n"
"#course_assessment_previous:hover, #course_assessment_next:hover {\n"
"    background-color: #F5F5F5;\n"
"}\n"
"#course_assessment_page_1, #course_assessment_page_2, #course_assessment_page_3, #course_assessment_page_8, #course_assessment_page_9, #course_assessment_page_10 {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #444;\n"
"    padding: 6px 10px;\n"
"}\n"
"#course_assessment_page_1 {\n"
"    background-color: #E0E0E0;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"#space {\n"
"    color: #777;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(801, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu.setObjectName("menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout.setSpacing(11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.brand = QtWidgets.QLabel(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brand.sizePolicy().hasHeightForWidth())
        self.brand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.brand.setFont(font)
        self.brand.setStyleSheet("")
        self.brand.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.brand.setObjectName("brand")
        self.verticalLayout.addWidget(self.brand)
        self.line_1 = QtWidgets.QFrame(parent=self.menu)
        self.line_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout.addWidget(self.line_1)
        self.frame_2 = QtWidgets.QFrame(parent=self.menu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menu_course = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_course.sizePolicy().hasHeightForWidth())
        self.menu_course.setSizePolicy(sizePolicy)
        self.menu_course.setStyleSheet("")
        self.menu_course.setObjectName("menu_course")
        self.verticalLayout_3.addWidget(self.menu_course)
        self.menu_student = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_student.sizePolicy().hasHeightForWidth())
        self.menu_student.setSizePolicy(sizePolicy)
        self.menu_student.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.menu_student.setStyleSheet("")
        self.menu_student.setObjectName("menu_student")
        self.verticalLayout_3.addWidget(self.menu_student)
        self.menu_analysis = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_analysis.sizePolicy().hasHeightForWidth())
        self.menu_analysis.setSizePolicy(sizePolicy)
        self.menu_analysis.setStyleSheet("")
        self.menu_analysis.setObjectName("menu_analysis")
        self.verticalLayout_3.addWidget(self.menu_analysis)
        self.menu_payment = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_payment.sizePolicy().hasHeightForWidth())
        self.menu_payment.setSizePolicy(sizePolicy)
        self.menu_payment.setMinimumSize(QtCore.QSize(150, 28))
        self.menu_payment.setStyleSheet("")
        self.menu_payment.setObjectName("menu_payment")
        self.verticalLayout_3.addWidget(self.menu_payment)
        self.verticalLayout.addWidget(self.frame_2)
        self.line_2 = QtWidgets.QFrame(parent=self.menu)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.menu_setting = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_setting.sizePolicy().hasHeightForWidth())
        self.menu_setting.setSizePolicy(sizePolicy)
        self.menu_setting.setMinimumSize(QtCore.QSize(60, 12))
        self.menu_setting.setStyleSheet("")
        self.menu_setting.setObjectName("menu_setting")
        self.verticalLayout.addWidget(self.menu_setting)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.menu_logout = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_logout.sizePolicy().hasHeightForWidth())
        self.menu_logout.setSizePolicy(sizePolicy)
        self.menu_logout.setStyleSheet("")
        self.menu_logout.setObjectName("menu_logout")
        self.verticalLayout.addWidget(self.menu_logout)
        self.horizontalLayout.addWidget(self.menu)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QWidget(parent=self.frame_3)
        self.header.setMinimumSize(QtCore.QSize(50, 50))
        self.header.setStyleSheet("background-color: #f9f9f9;")
        self.header.setObjectName("header")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_9.setContentsMargins(0, 0, 11, 0)
        self.horizontalLayout_9.setSpacing(7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.header_result = QtWidgets.QLabel(parent=self.header)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.header_result.setFont(font)
        self.header_result.setStyleSheet("color:#757575")
        self.header_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.header_result.setObjectName("header_result")
        self.horizontalLayout_9.addWidget(self.header_result)
        self.header_assessment = QtWidgets.QLabel(parent=self.header)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.header_assessment.setFont(font)
        self.header_assessment.setStyleSheet("color: black")
        self.header_assessment.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.header_assessment.setObjectName("header_assessment")
        self.horizontalLayout_9.addWidget(self.header_assessment)
        self.header_student = QtWidgets.QLabel(parent=self.header)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.header_student.setFont(font)
        self.header_student.setStyleSheet("color:#757575")
        self.header_student.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.header_student.setObjectName("header_student")
        self.horizontalLayout_9.addWidget(self.header_student)
        self.verticalLayout_2.addWidget(self.header)
        self.option = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option.sizePolicy().hasHeightForWidth())
        self.option.setSizePolicy(sizePolicy)
        self.option.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.option.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.option.setObjectName("option")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.option)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search = QtWidgets.QFrame(parent=self.option)
        self.search.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.search.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.search.setObjectName("search")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.search)
        self.horizontalLayout_3.setContentsMargins(-1, 11, -1, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.course_assessment_search_comboBox = QtWidgets.QComboBox(parent=self.search)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_search_comboBox.sizePolicy().hasHeightForWidth())
        self.course_assessment_search_comboBox.setSizePolicy(sizePolicy)
        self.course_assessment_search_comboBox.setMinimumSize(QtCore.QSize(165, 31))
        self.course_assessment_search_comboBox.setStyleSheet("")
        self.course_assessment_search_comboBox.setObjectName("course_assessment_search_comboBox")
        self.course_assessment_search_comboBox.addItem("")
        self.course_assessment_search_comboBox.addItem("")
        self.course_assessment_search_comboBox.addItem("")
        self.course_assessment_search_comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.course_assessment_search_comboBox)
        self.course_assessment_search_lineEdit = QtWidgets.QLineEdit(parent=self.search)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_search_lineEdit.sizePolicy().hasHeightForWidth())
        self.course_assessment_search_lineEdit.setSizePolicy(sizePolicy)
        self.course_assessment_search_lineEdit.setMinimumSize(QtCore.QSize(260, 31))
        self.course_assessment_search_lineEdit.setObjectName("course_assessment_search_lineEdit")
        self.horizontalLayout_3.addWidget(self.course_assessment_search_lineEdit)
        self.horizontalLayout_2.addWidget(self.search)
        self.frame_5 = QtWidgets.QFrame(parent=self.option)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(-1, 11, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.course_assessment_filter = QtWidgets.QPushButton(parent=self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_filter.sizePolicy().hasHeightForWidth())
        self.course_assessment_filter.setSizePolicy(sizePolicy)
        self.course_assessment_filter.setMinimumSize(QtCore.QSize(70, 30))
        self.course_assessment_filter.setObjectName("course_assessment_filter")
        self.horizontalLayout_4.addWidget(self.course_assessment_filter)
        self.course_assessment_create = QtWidgets.QPushButton(parent=self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_create.sizePolicy().hasHeightForWidth())
        self.course_assessment_create.setSizePolicy(sizePolicy)
        self.course_assessment_create.setMinimumSize(QtCore.QSize(82, 30))
        self.course_assessment_create.setObjectName("course_assessment_create")
        self.horizontalLayout_4.addWidget(self.course_assessment_create)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.option)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(165, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.course_assessment_table = QtWidgets.QTableWidget(parent=self.frame_6)
        self.course_assessment_table.setStyleSheet("color: black")
        self.course_assessment_table.setObjectName("course_assessment_table")
        self.course_assessment_table.setColumnCount(4)
        self.course_assessment_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.course_assessment_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.course_assessment_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.course_assessment_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.course_assessment_table.setHorizontalHeaderItem(3, item)
        self.course_assessment_table.horizontalHeader().setDefaultSectionSize(152)
        self.horizontalLayout_8.addWidget(self.course_assessment_table)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.course_assessment_previous = QtWidgets.QPushButton(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_previous.sizePolicy().hasHeightForWidth())
        self.course_assessment_previous.setSizePolicy(sizePolicy)
        self.course_assessment_previous.setObjectName("course_assessment_previous")
        self.horizontalLayout_6.addWidget(self.course_assessment_previous)
        spacerItem3 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.course_assessment_page = QtWidgets.QWidget(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_page.sizePolicy().hasHeightForWidth())
        self.course_assessment_page.setSizePolicy(sizePolicy)
        self.course_assessment_page.setMinimumSize(QtCore.QSize(350, 0))
        self.course_assessment_page.setObjectName("course_assessment_page")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.course_assessment_page)
        self.horizontalLayout_7.setContentsMargins(11, -1, 11, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.course_assessment_page_1 = QtWidgets.QPushButton(parent=self.course_assessment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_page_1.sizePolicy().hasHeightForWidth())
        self.course_assessment_page_1.setSizePolicy(sizePolicy)
        self.course_assessment_page_1.setMinimumSize(QtCore.QSize(28, 0))
        self.course_assessment_page_1.setObjectName("course_assessment_page_1")
        self.horizontalLayout_7.addWidget(self.course_assessment_page_1)
        self.course_assessment_page_2 = QtWidgets.QPushButton(parent=self.course_assessment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_page_2.sizePolicy().hasHeightForWidth())
        self.course_assessment_page_2.setSizePolicy(sizePolicy)
        self.course_assessment_page_2.setMinimumSize(QtCore.QSize(28, 0))
        self.course_assessment_page_2.setObjectName("course_assessment_page_2")
        self.horizontalLayout_7.addWidget(self.course_assessment_page_2)
        self.course_assessment_page_8 = QtWidgets.QPushButton(parent=self.course_assessment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_page_8.sizePolicy().hasHeightForWidth())
        self.course_assessment_page_8.setSizePolicy(sizePolicy)
        self.course_assessment_page_8.setMinimumSize(QtCore.QSize(28, 0))
        self.course_assessment_page_8.setObjectName("course_assessment_page_8")
        self.horizontalLayout_7.addWidget(self.course_assessment_page_8)
        self.course_assessment_space = QtWidgets.QLabel(parent=self.course_assessment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_space.sizePolicy().hasHeightForWidth())
        self.course_assessment_space.setSizePolicy(sizePolicy)
        self.course_assessment_space.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.course_assessment_space.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.course_assessment_space.setObjectName("course_assessment_space")
        self.horizontalLayout_7.addWidget(self.course_assessment_space)
        self.course_assessment_page_10 = QtWidgets.QPushButton(parent=self.course_assessment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_page_10.sizePolicy().hasHeightForWidth())
        self.course_assessment_page_10.setSizePolicy(sizePolicy)
        self.course_assessment_page_10.setMinimumSize(QtCore.QSize(28, 0))
        self.course_assessment_page_10.setObjectName("course_assessment_page_10")
        self.horizontalLayout_7.addWidget(self.course_assessment_page_10)
        self.course_assessment_page_9 = QtWidgets.QPushButton(parent=self.course_assessment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_page_9.sizePolicy().hasHeightForWidth())
        self.course_assessment_page_9.setSizePolicy(sizePolicy)
        self.course_assessment_page_9.setMinimumSize(QtCore.QSize(28, 0))
        self.course_assessment_page_9.setObjectName("course_assessment_page_9")
        self.horizontalLayout_7.addWidget(self.course_assessment_page_9)
        self.course_assessment_page_3 = QtWidgets.QPushButton(parent=self.course_assessment_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_page_3.sizePolicy().hasHeightForWidth())
        self.course_assessment_page_3.setSizePolicy(sizePolicy)
        self.course_assessment_page_3.setMinimumSize(QtCore.QSize(28, 0))
        self.course_assessment_page_3.setObjectName("course_assessment_page_3")
        self.horizontalLayout_7.addWidget(self.course_assessment_page_3)
        self.horizontalLayout_6.addWidget(self.course_assessment_page)
        spacerItem4 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.course_assessment_next = QtWidgets.QPushButton(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_assessment_next.sizePolicy().hasHeightForWidth())
        self.course_assessment_next.setSizePolicy(sizePolicy)
        self.course_assessment_next.setObjectName("course_assessment_next")
        self.horizontalLayout_6.addWidget(self.course_assessment_next)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame_3)
        self.horizontalLayout_5.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.brand.setText(_translate("MainWindow", "DUKI"))
        self.menu_course.setText(_translate("MainWindow", "Course"))
        self.menu_student.setText(_translate("MainWindow", "Student"))
        self.menu_analysis.setText(_translate("MainWindow", "Analysis"))
        self.menu_payment.setText(_translate("MainWindow", "Payment"))
        self.menu_setting.setText(_translate("MainWindow", "Setting"))
        self.menu_logout.setText(_translate("MainWindow", "Log out"))
        self.header_result.setText(_translate("MainWindow", "Result"))
        self.header_assessment.setText(_translate("MainWindow", "Assessments"))
        self.header_student.setText(_translate("MainWindow", "Student"))
        self.course_assessment_search_comboBox.setItemText(0, _translate("MainWindow", "ID Assessment"))
        self.course_assessment_search_comboBox.setItemText(1, _translate("MainWindow", "Assessment type"))
        self.course_assessment_search_comboBox.setItemText(2, _translate("MainWindow", "Date"))
        self.course_assessment_search_comboBox.setItemText(3, _translate("MainWindow", "Weight"))
        self.course_assessment_search_lineEdit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.course_assessment_filter.setText(_translate("MainWindow", "Filter"))
        self.course_assessment_create.setText(_translate("MainWindow", "+ Create"))
        item = self.course_assessment_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID Assessment"))
        item = self.course_assessment_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Assessment type"))
        item = self.course_assessment_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
        item = self.course_assessment_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Weight"))
        self.course_assessment_previous.setText(_translate("MainWindow", "<- Previous"))
        self.course_assessment_page_1.setText(_translate("MainWindow", "1"))
        self.course_assessment_page_2.setText(_translate("MainWindow", "2"))
        self.course_assessment_page_8.setText(_translate("MainWindow", "3"))
        self.course_assessment_space.setText(_translate("MainWindow", "..."))
        self.course_assessment_page_10.setText(_translate("MainWindow", "8"))
        self.course_assessment_page_9.setText(_translate("MainWindow", "9"))
        self.course_assessment_page_3.setText(_translate("MainWindow", "10"))
        self.course_assessment_next.setText(_translate("MainWindow", "   Next -> "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
