# Form implementation generated from reading ui file 'C:\Users\phamn\Documents\course-management-ml\ui\course.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 614)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #f6f6f6;\n"
"}\n"
"QFrame {\n"
"    background-color: #f6f6f6;\n"
"}\n"
"#centralwidget{\n"
"    background-color: #f6f6f6;\n"
"}\n"
"#menu {\n"
"    background-color: #f9f9f9;\n"
"    border-right: 1px solid #e0e0e0;\n"
"}\n"
"QLabel#brand {\n"
"    color: black;\n"
"}\n"
"\n"
"#menu_analysis,\n"
"#menu_course,\n"
"#menu_payment,\n"
"#menu_student,\n"
"#menu_setting {\n"
"    text-align: left;\n"
"    padding: 8px 20px;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"#menu_analysis:hover,\n"
"#menu_course:hover,\n"
"#menu_logout:hover,\n"
"#menu_payment:hover,\n"
"#menu_student:hover,\n"
"#menu_setting:hover {\n"
"    background-color: #eaeaea;\n"
"}\n"
"#menu_logout {\n"
"    text-align: left;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    color: red;\n"
"}\n"
"#lineEdit_search {\n"
"    background-color: #F8F8F8;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius-right: 10px;\n"
"    padding: 6px 12px;\n"
"    color: #555;\n"
"}\n"
"#lineEdit_search:focus {\n"
"    border: 2px solid #A0A0A0;\n"
"}\n"
"#btn_search {\n"
"    border:none;\n"
"}\n"
"#comboBox_search {\n"
"    background-color: #2E2E2E;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2E2E2E;\n"
"    color: white;\n"
"    selection-background-color: #444444;\n"
"    selection-color: white;\n"
"}\n"
"#btn_create {\n"
"    background-color: #4C8BF5;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-weight: bold;\n"
"}\n"
"#btn_create:hover {\n"
"    background-color: #3B73E0;\n"
"}\n"
"#btn_filter {\n"
"    background-color: #F4F4F4;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    color: black;\n"
"}\n"
"#btn_filter:hover {\n"
"    background-color: #EAEAEA;\n"
"}\n"
"#header{\n"
"    background-color: #f9f9f9;\n"
"    color: black;\n"
"}\n"
"#btn_previous, #btn_next {\n"
"    background-color: white;\n"
"    color: #2E3A59;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    font-weight: 500;\n"
"}\n"
"#btn_previous:hover, #btn_next:hover {\n"
"    background-color: #F5F5F5;\n"
"}\n"
"#course_page_1, #course_page_2, #course_page_3, #course_page_8, #course_page_9, #course_page_10 {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #444;\n"
"    padding: 6px 10px;\n"
"}\n"
"#course_page_1:hover, #course_page_2:hover, #course_page_3:hover, #course_page_8:hover, #course_page_9:hover, #course_page_10:hover {\n"
"    background-color: #E0E0E0;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"#space {\n"
"    color: #777;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(801, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu.setObjectName("menu")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_15.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout_15.setSpacing(11)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.brand = QtWidgets.QLabel(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brand.sizePolicy().hasHeightForWidth())
        self.brand.setSizePolicy(sizePolicy)
        self.brand.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.brand.setFont(font)
        self.brand.setStyleSheet("")
        self.brand.setText("")
        self.brand.setPixmap(QtGui.QPixmap(":/Images/images/Logo DUKI.png"))
        self.brand.setScaledContents(True)
        self.brand.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.brand.setObjectName("brand")
        self.verticalLayout_15.addWidget(self.brand)
        self.line_9 = QtWidgets.QFrame(parent=self.menu)
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_15.addWidget(self.line_9)
        self.frame_5 = QtWidgets.QFrame(parent=self.menu)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.menu_course = QtWidgets.QPushButton(parent=self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_course.sizePolicy().hasHeightForWidth())
        self.menu_course.setSizePolicy(sizePolicy)
        self.menu_course.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/Course.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_course.setIcon(icon)
        self.menu_course.setObjectName("menu_course")
        self.verticalLayout_16.addWidget(self.menu_course)
        self.menu_student = QtWidgets.QPushButton(parent=self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_student.sizePolicy().hasHeightForWidth())
        self.menu_student.setSizePolicy(sizePolicy)
        self.menu_student.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.menu_student.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/Student1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_student.setIcon(icon1)
        self.menu_student.setObjectName("menu_student")
        self.verticalLayout_16.addWidget(self.menu_student)
        self.menu_analysis = QtWidgets.QPushButton(parent=self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_analysis.sizePolicy().hasHeightForWidth())
        self.menu_analysis.setSizePolicy(sizePolicy)
        self.menu_analysis.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/Analysis.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_analysis.setIcon(icon2)
        self.menu_analysis.setObjectName("menu_analysis")
        self.verticalLayout_16.addWidget(self.menu_analysis)
        self.menu_payment = QtWidgets.QPushButton(parent=self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_payment.sizePolicy().hasHeightForWidth())
        self.menu_payment.setSizePolicy(sizePolicy)
        self.menu_payment.setMinimumSize(QtCore.QSize(150, 28))
        self.menu_payment.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/Payment.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_payment.setIcon(icon3)
        self.menu_payment.setObjectName("menu_payment")
        self.verticalLayout_16.addWidget(self.menu_payment)
        self.verticalLayout_15.addWidget(self.frame_5)
        self.line_10 = QtWidgets.QFrame(parent=self.menu)
        self.line_10.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_15.addWidget(self.line_10)
        self.menu_setting = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_setting.sizePolicy().hasHeightForWidth())
        self.menu_setting.setSizePolicy(sizePolicy)
        self.menu_setting.setMinimumSize(QtCore.QSize(60, 12))
        self.menu_setting.setStyleSheet("")
        self.menu_setting.setObjectName("menu_setting")
        self.verticalLayout_15.addWidget(self.menu_setting)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.menu_logout = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_logout.sizePolicy().hasHeightForWidth())
        self.menu_logout.setSizePolicy(sizePolicy)
        self.menu_logout.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.menu_logout.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/Log_Out.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_logout.setIcon(icon4)
        self.menu_logout.setObjectName("menu_logout")
        self.verticalLayout_15.addWidget(self.menu_logout)
        self.horizontalLayout.addWidget(self.menu)
        self.frame_main = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_main.sizePolicy().hasHeightForWidth())
        self.frame_main.setSizePolicy(sizePolicy)
        self.frame_main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_topbar = QtWidgets.QFrame(parent=self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_topbar.sizePolicy().hasHeightForWidth())
        self.frame_topbar.setSizePolicy(sizePolicy)
        self.frame_topbar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_topbar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_topbar.setObjectName("frame_topbar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_topbar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2.addWidget(self.frame_topbar)
        self.header = QtWidgets.QLabel(parent=self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.header.setFont(font)
        self.header.setObjectName("header")
        self.verticalLayout_2.addWidget(self.header)
        self.frame_content = QtWidgets.QFrame(parent=self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_content.sizePolicy().hasHeightForWidth())
        self.frame_content.setSizePolicy(sizePolicy)
        self.frame_content.setMinimumSize(QtCore.QSize(165, 0))
        self.frame_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_content.setObjectName("frame_content")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_content)
        self.gridLayout.setObjectName("gridLayout")
        self.course_5 = QtWidgets.QFrame(parent=self.frame_content)
        self.course_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.course_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.course_5.setObjectName("course_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.course_5)
        self.verticalLayout_10.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.image_5 = QtWidgets.QWidget(parent=self.course_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_5.sizePolicy().hasHeightForWidth())
        self.image_5.setSizePolicy(sizePolicy)
        self.image_5.setObjectName("image_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.image_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.image_course_5 = QtWidgets.QLabel(parent=self.image_5)
        self.image_course_5.setText("")
        self.image_course_5.setScaledContents(True)
        self.image_course_5.setObjectName("image_course_5")
        self.gridLayout_6.addWidget(self.image_course_5, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.image_5)
        self.course_code_module5 = QtWidgets.QLabel(parent=self.course_5)
        self.course_code_module5.setStyleSheet("color: white;\n"
"background-color: black")
        self.course_code_module5.setText("")
        self.course_code_module5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.course_code_module5.setObjectName("course_code_module5")
        self.verticalLayout_10.addWidget(self.course_code_module5)
        self.course_code_presentation5 = QtWidgets.QLabel(parent=self.course_5)
        self.course_code_presentation5.setStyleSheet("color: black")
        self.course_code_presentation5.setText("")
        self.course_code_presentation5.setObjectName("course_code_presentation5")
        self.verticalLayout_10.addWidget(self.course_code_presentation5)
        self.frame_module_presentation5 = QtWidgets.QFrame(parent=self.course_5)
        self.frame_module_presentation5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_module_presentation5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_module_presentation5.setObjectName("frame_module_presentation5")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_module_presentation5)
        self.horizontalLayout_14.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.course_module_presentation5 = QtWidgets.QLabel(parent=self.frame_module_presentation5)
        self.course_module_presentation5.setStyleSheet("color: red")
        self.course_module_presentation5.setObjectName("course_module_presentation5")
        self.horizontalLayout_14.addWidget(self.course_module_presentation5)
        self.presentation5 = QtWidgets.QLabel(parent=self.frame_module_presentation5)
        self.presentation5.setStyleSheet("color: red")
        self.presentation5.setText("")
        self.presentation5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.presentation5.setObjectName("presentation5")
        self.horizontalLayout_14.addWidget(self.presentation5)
        self.verticalLayout_10.addWidget(self.frame_module_presentation5)
        self.gridLayout.addWidget(self.course_5, 1, 1, 1, 1)
        self.course_6 = QtWidgets.QFrame(parent=self.frame_content)
        self.course_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.course_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.course_6.setObjectName("course_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.course_6)
        self.verticalLayout_12.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.image_6 = QtWidgets.QWidget(parent=self.course_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_6.sizePolicy().hasHeightForWidth())
        self.image_6.setSizePolicy(sizePolicy)
        self.image_6.setObjectName("image_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.image_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.image_course_6 = QtWidgets.QLabel(parent=self.image_6)
        self.image_course_6.setText("")
        self.image_course_6.setScaledContents(True)
        self.image_course_6.setObjectName("image_course_6")
        self.gridLayout_7.addWidget(self.image_course_6, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.image_6)
        self.course_code_module6 = QtWidgets.QLabel(parent=self.course_6)
        self.course_code_module6.setStyleSheet("color: white;\n"
"background-color: black")
        self.course_code_module6.setText("")
        self.course_code_module6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.course_code_module6.setObjectName("course_code_module6")
        self.verticalLayout_12.addWidget(self.course_code_module6)
        self.course_code_presentation6 = QtWidgets.QLabel(parent=self.course_6)
        self.course_code_presentation6.setStyleSheet("color: black")
        self.course_code_presentation6.setText("")
        self.course_code_presentation6.setObjectName("course_code_presentation6")
        self.verticalLayout_12.addWidget(self.course_code_presentation6)
        self.frame_module_presentation6 = QtWidgets.QFrame(parent=self.course_6)
        self.frame_module_presentation6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_module_presentation6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_module_presentation6.setObjectName("frame_module_presentation6")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_module_presentation6)
        self.horizontalLayout_16.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.course_module_presentation6 = QtWidgets.QLabel(parent=self.frame_module_presentation6)
        self.course_module_presentation6.setStyleSheet("color: red")
        self.course_module_presentation6.setObjectName("course_module_presentation6")
        self.horizontalLayout_16.addWidget(self.course_module_presentation6)
        self.presentation6 = QtWidgets.QLabel(parent=self.frame_module_presentation6)
        self.presentation6.setStyleSheet("color: red")
        self.presentation6.setText("")
        self.presentation6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.presentation6.setObjectName("presentation6")
        self.horizontalLayout_16.addWidget(self.presentation6)
        self.verticalLayout_12.addWidget(self.frame_module_presentation6)
        self.gridLayout.addWidget(self.course_6, 1, 2, 1, 1)
        self.course_1 = QtWidgets.QFrame(parent=self.frame_content)
        self.course_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.course_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.course_1.setObjectName("course_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.course_1)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.image_1 = QtWidgets.QWidget(parent=self.course_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_1.sizePolicy().hasHeightForWidth())
        self.image_1.setSizePolicy(sizePolicy)
        self.image_1.setObjectName("image_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.image_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.image_course_1 = QtWidgets.QLabel(parent=self.image_1)
        self.image_course_1.setText("")
        self.image_course_1.setScaledContents(True)
        self.image_course_1.setObjectName("image_course_1")
        self.gridLayout_2.addWidget(self.image_course_1, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.image_1)
        self.course_code_module1 = QtWidgets.QLabel(parent=self.course_1)
        self.course_code_module1.setStyleSheet("color: white;\n"
"background-color: black")
        self.course_code_module1.setText("")
        self.course_code_module1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.course_code_module1.setObjectName("course_code_module1")
        self.verticalLayout_4.addWidget(self.course_code_module1)
        self.course_code_presentation1 = QtWidgets.QLabel(parent=self.course_1)
        self.course_code_presentation1.setStyleSheet("color: black")
        self.course_code_presentation1.setText("")
        self.course_code_presentation1.setObjectName("course_code_presentation1")
        self.verticalLayout_4.addWidget(self.course_code_presentation1)
        self.frame_module_presentation1 = QtWidgets.QFrame(parent=self.course_1)
        self.frame_module_presentation1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_module_presentation1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_module_presentation1.setObjectName("frame_module_presentation1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_module_presentation1)
        self.horizontalLayout_8.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.course_module_presentation1 = QtWidgets.QLabel(parent=self.frame_module_presentation1)
        self.course_module_presentation1.setStyleSheet("color: red")
        self.course_module_presentation1.setObjectName("course_module_presentation1")
        self.horizontalLayout_8.addWidget(self.course_module_presentation1)
        self.presentation1 = QtWidgets.QLabel(parent=self.frame_module_presentation1)
        self.presentation1.setStyleSheet("color: red")
        self.presentation1.setText("")
        self.presentation1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.presentation1.setObjectName("presentation1")
        self.horizontalLayout_8.addWidget(self.presentation1)
        self.verticalLayout_4.addWidget(self.frame_module_presentation1)
        self.gridLayout.addWidget(self.course_1, 0, 0, 1, 1)
        self.course_4 = QtWidgets.QFrame(parent=self.frame_content)
        self.course_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.course_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.course_4.setObjectName("course_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.course_4)
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.image_4 = QtWidgets.QWidget(parent=self.course_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_4.sizePolicy().hasHeightForWidth())
        self.image_4.setSizePolicy(sizePolicy)
        self.image_4.setObjectName("image_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.image_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.image_course_4 = QtWidgets.QLabel(parent=self.image_4)
        self.image_course_4.setText("")
        self.image_course_4.setScaledContents(True)
        self.image_course_4.setObjectName("image_course_4")
        self.gridLayout_5.addWidget(self.image_course_4, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.image_4)
        self.course_code_module4 = QtWidgets.QLabel(parent=self.course_4)
        self.course_code_module4.setStyleSheet("color: white;\n"
"background-color: black")
        self.course_code_module4.setText("")
        self.course_code_module4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.course_code_module4.setObjectName("course_code_module4")
        self.verticalLayout_5.addWidget(self.course_code_module4)
        self.course_code_presentation4 = QtWidgets.QLabel(parent=self.course_4)
        self.course_code_presentation4.setStyleSheet("color: black")
        self.course_code_presentation4.setText("")
        self.course_code_presentation4.setObjectName("course_code_presentation4")
        self.verticalLayout_5.addWidget(self.course_code_presentation4)
        self.frame_module_presentation4 = QtWidgets.QFrame(parent=self.course_4)
        self.frame_module_presentation4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_module_presentation4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_module_presentation4.setObjectName("frame_module_presentation4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_module_presentation4)
        self.horizontalLayout_9.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.course_module_presentation4 = QtWidgets.QLabel(parent=self.frame_module_presentation4)
        self.course_module_presentation4.setStyleSheet("color: red")
        self.course_module_presentation4.setObjectName("course_module_presentation4")
        self.horizontalLayout_9.addWidget(self.course_module_presentation4)
        self.presentation4 = QtWidgets.QLabel(parent=self.frame_module_presentation4)
        self.presentation4.setStyleSheet("color: red")
        self.presentation4.setText("")
        self.presentation4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.presentation4.setObjectName("presentation4")
        self.horizontalLayout_9.addWidget(self.presentation4)
        self.verticalLayout_5.addWidget(self.frame_module_presentation4)
        self.gridLayout.addWidget(self.course_4, 1, 0, 1, 1)
        self.course_2 = QtWidgets.QFrame(parent=self.frame_content)
        self.course_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.course_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.course_2.setObjectName("course_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.course_2)
        self.verticalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.image_2 = QtWidgets.QWidget(parent=self.course_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_2.sizePolicy().hasHeightForWidth())
        self.image_2.setSizePolicy(sizePolicy)
        self.image_2.setObjectName("image_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.image_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.image_course_2 = QtWidgets.QLabel(parent=self.image_2)
        self.image_course_2.setText("")
        self.image_course_2.setScaledContents(True)
        self.image_course_2.setObjectName("image_course_2")
        self.gridLayout_3.addWidget(self.image_course_2, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.image_2)
        self.course_code_module2 = QtWidgets.QLabel(parent=self.course_2)
        self.course_code_module2.setStyleSheet("color: white;\n"
"background-color: black")
        self.course_code_module2.setText("")
        self.course_code_module2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.course_code_module2.setObjectName("course_code_module2")
        self.verticalLayout_9.addWidget(self.course_code_module2)
        self.course_code_presentation2 = QtWidgets.QLabel(parent=self.course_2)
        self.course_code_presentation2.setStyleSheet("color: black")
        self.course_code_presentation2.setText("")
        self.course_code_presentation2.setObjectName("course_code_presentation2")
        self.verticalLayout_9.addWidget(self.course_code_presentation2)
        self.frame_module_presentation2 = QtWidgets.QFrame(parent=self.course_2)
        self.frame_module_presentation2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_module_presentation2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_module_presentation2.setObjectName("frame_module_presentation2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_module_presentation2)
        self.horizontalLayout_13.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.course_module_presentation2 = QtWidgets.QLabel(parent=self.frame_module_presentation2)
        self.course_module_presentation2.setStyleSheet("color: red")
        self.course_module_presentation2.setObjectName("course_module_presentation2")
        self.horizontalLayout_13.addWidget(self.course_module_presentation2)
        self.presentation2 = QtWidgets.QLabel(parent=self.frame_module_presentation2)
        self.presentation2.setStyleSheet("color: red")
        self.presentation2.setText("")
        self.presentation2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.presentation2.setObjectName("presentation2")
        self.horizontalLayout_13.addWidget(self.presentation2)
        self.verticalLayout_9.addWidget(self.frame_module_presentation2)
        self.gridLayout.addWidget(self.course_2, 0, 1, 1, 1)
        self.course_3 = QtWidgets.QFrame(parent=self.frame_content)
        self.course_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.course_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.course_3.setObjectName("course_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.course_3)
        self.verticalLayout_11.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.image_3 = QtWidgets.QWidget(parent=self.course_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_3.sizePolicy().hasHeightForWidth())
        self.image_3.setSizePolicy(sizePolicy)
        self.image_3.setObjectName("image_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.image_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.image_course_3 = QtWidgets.QLabel(parent=self.image_3)
        self.image_course_3.setText("")
        self.image_course_3.setScaledContents(True)
        self.image_course_3.setObjectName("image_course_3")
        self.gridLayout_4.addWidget(self.image_course_3, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.image_3)
        self.course_code_module3 = QtWidgets.QLabel(parent=self.course_3)
        self.course_code_module3.setStyleSheet("color: white;\n"
"background-color: black")
        self.course_code_module3.setText("")
        self.course_code_module3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.course_code_module3.setObjectName("course_code_module3")
        self.verticalLayout_11.addWidget(self.course_code_module3)
        self.course_code_presentation3 = QtWidgets.QLabel(parent=self.course_3)
        self.course_code_presentation3.setStyleSheet("color: black")
        self.course_code_presentation3.setText("")
        self.course_code_presentation3.setObjectName("course_code_presentation3")
        self.verticalLayout_11.addWidget(self.course_code_presentation3)
        self.frame_module_presentation3 = QtWidgets.QFrame(parent=self.course_3)
        self.frame_module_presentation3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_module_presentation3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_module_presentation3.setObjectName("frame_module_presentation3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_module_presentation3)
        self.horizontalLayout_15.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.course_module_presentation3 = QtWidgets.QLabel(parent=self.frame_module_presentation3)
        self.course_module_presentation3.setStyleSheet("color: red")
        self.course_module_presentation3.setObjectName("course_module_presentation3")
        self.horizontalLayout_15.addWidget(self.course_module_presentation3)
        self.presentation3 = QtWidgets.QLabel(parent=self.frame_module_presentation3)
        self.presentation3.setStyleSheet("color: red")
        self.presentation3.setText("")
        self.presentation3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.presentation3.setObjectName("presentation3")
        self.horizontalLayout_15.addWidget(self.presentation3)
        self.verticalLayout_11.addWidget(self.frame_module_presentation3)
        self.gridLayout.addWidget(self.course_3, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_content)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_previous = QtWidgets.QPushButton(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_previous.sizePolicy().hasHeightForWidth())
        self.btn_previous.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/le-Photoroom.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_previous.setIcon(icon5)
        self.btn_previous.setObjectName("btn_previous")
        self.horizontalLayout_10.addWidget(self.btn_previous)
        spacerItem1 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.btn_next = QtWidgets.QPushButton(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next.sizePolicy().hasHeightForWidth())
        self.btn_next.setSizePolicy(sizePolicy)
        self.btn_next.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/images/icons/Course/ri-Photoroom.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_next.setIcon(icon6)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_10.addWidget(self.btn_next)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame_main)
        self.horizontalLayout_5.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_course.setText(_translate("MainWindow", "Course"))
        self.menu_student.setText(_translate("MainWindow", "Student"))
        self.menu_analysis.setText(_translate("MainWindow", "Analysis"))
        self.menu_payment.setText(_translate("MainWindow", "Payment*"))
        self.menu_setting.setText(_translate("MainWindow", "Setting*"))
        self.menu_logout.setText(_translate("MainWindow", "Log out"))
        self.header.setText(_translate("MainWindow", "  Course"))
        self.course_module_presentation5.setText(_translate("MainWindow", "Lecture counts"))
        self.course_module_presentation6.setText(_translate("MainWindow", "Lecture counts"))
        self.course_module_presentation1.setText(_translate("MainWindow", "Lecture counts"))
        self.course_module_presentation4.setText(_translate("MainWindow", "Lecture counts"))
        self.course_module_presentation2.setText(_translate("MainWindow", "Lecture counts"))
        self.course_module_presentation3.setText(_translate("MainWindow", "Lecture counts"))
        self.btn_previous.setText(_translate("MainWindow", "Previous"))
        self.btn_next.setText(_translate("MainWindow", "   Next "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
